package com.learn_api_kotlin.learning.exception

class DataAlreadyExistsException(message: String ) : RuntimeException(message)
